jobs = [
    "Analyste de données",
    "Analyste de la qualité des données",
    "Architecte de données",
    "Chercheur en apprentissage automatique",
    "Chercheur en intelligence artificielle",
    "Consultant en analyse de données",
    "Scientifique des données",
    "Développeur d'apprentissage automatique",
    "Développeur de logiciels d'intelligence artificielle",
    "Expert en visualisation de données",
    "Ingénieur en données",
    "Ingénieur en apprentissage automatique",
    "Spécialiste de gros données",
    "Spécialiste en traitement du langage naturel",
    "Statisticien",
    "Concepteur de plateforme de données",
    "Développeur de pipeline de données",
    "Développeur de logiciels de traitement de données",
    "Développeur de systèmes de base de données",
    "Développeur de systèmes d'information",
    "Développeur Python",
    "Développeur Java",
    "Développeur SQL",
    "Développeur Hadoop",
    "Développeur TensorFlow",
    "Développeur Keras",
    "Développeur PyTorch",
    "Administrateur AWS",
    "Architecte Azure",
    "Spécialiste de Google Cloud Platform",
    # Ajout de nouveaux emplois
    "Ingénieur en traitement du signal",
    "Développeur de logiciels de fouille de données",
    "Analyste en apprentissage automatique",
    "Administrateur de base de données",
    "Architecte de solutions de données",
    "Analyste de données financières",
    "Chercheur en vision par ordinateur",
    "Développeur d'applications cloud",
    "Expert en apprentissage automatique pour la santé",
    "Analyste en analyse de texte",
    "Ingénieur Big Data",
    "Développeur de logiciels d'analyse de données",
    "Spécialiste en apprentissage automatique distribué",
    "Analyste de données marketing",
    "Ingénieur en traitement du langage naturel",
    "Développeur de systèmes de stockage de données",
    "Concepteur de bases de données",
    "Développeur de logiciels de fouille de texte",
    "Analyste en traitement d'image",
    "Ingénieur DevOps cloud",
    "Spécialiste en traitement de données biomédicales",
    "Consultant en intelligence d'affaires",
    "Développeur de logiciels d'analyse prédictive",
    "Ingénieur en apprentissage automatique distribué",
    "Analyste de données de santé",
    "Développeur de systèmes de gestion de données",
    "Concepteur de modèles d'apprentissage automatique",
    "Spécialiste en bases de données NoSQL",
    "Développeur d'applications d'intelligence artificielle",
    "Analyste de données de vente",
    "Architecte de données cloud",
    "Développeur de logiciels d'analyse de texte",
    "Ingénieur en vision par ordinateur",
    "Spécialiste en apprentissage automatique pour les réseaux sociaux",

    "Analyste de données de vente",
    "Architecte de données cloud",
    "Développeur de logiciels d'analyse de texte",
    "Ingénieur en vision par ordinateur",
    "Spécialiste en apprentissage automatique pour les réseaux sociaux",
    "Analyste en optimisation des moteurs de recherche",
    "Développeur de logiciels de traitement du signal",
    "Architecte de données d'entreprise",
    "Ingénieur en sécurité des données",
    "Consultant en intégration de données",
    "Développeur de systèmes d'apprentissage automatique",
    "Spécialiste en exploration de données",
    "Analyste en intelligence compétitive",
    "Ingénieur en traitement du langage naturel médical",
    "Développeur de logiciels de recommandation",
    "Architecte de données de santé",
    "Analyste de données en temps réel",
    "Spécialiste en intégration de données cloud",
    "Ingénieur en automatisation des processus robotiques",
    "Développeur de logiciels d'apprentissage automatique distribué",
    "Expert en analytique prédictive",
    "Analyste en détection de fraude",
    "Ingénieur en traitement d'images médicales",
    "Développeur de solutions de traitement de données en temps réel",
    "Architecte de données financières",
    "Analyste en détection d'anomalies",
    "Spécialiste en bases de données relationnelles",
    "Ingénieur en optimisation de moteurs de recommandation",
    "Développeur de logiciels de traitement du langage naturel",
    "Analyste en cybersécurité des données",
    "Ingénieur en traitement de données géospatiales",
    "Architecte de solutions d'apprentissage automatique",
    "Spécialiste en bases de données distribuées",
    "Développeur de logiciels d'analyse des réseaux sociaux",
    "Analyste de données de transport",
    "Ingénieur en traitement du langage naturel juridique",
    "Développeur de solutions d'apprentissage automatique pour l'IoT",
    "Expert en analyse de données financières",
    "Analyste en prévision de la demande",
    "Ingénieur en vision par ordinateur médicale",
    "Architecte de données d'assurance",
    "Spécialiste en extraction de connaissances",
    "Développeur de logiciels de recommandation de contenu",
    "Analyste en analyse des médias sociaux",
    "Ingénieur en traitement de données environnementales",
    "Consultant en science des données",
    "Ingénieur en traitement de données biométriques",
    "Développeur de solutions d'analyse des sentiments",
    "Architecte de données de l'e-commerce",
    "Spécialiste en fouille de données textuelles",
    "Ingénieur en traitement de données de marketing",
    "Analyste en modélisation prédictive",
    "Développeur de logiciels d'analyse de données environnementales",
    "Ingénieur en vision par ordinateur pour la robotique",
    "Architecte de données de la logistique",

    "Architecte de données de l'e-commerce",
    "Spécialiste en fouille de données textuelles",
    "Ingénieur en traitement de données de marketing",
    "Analyste en modélisation prédictive",
    "Développeur de logiciels d'analyse de données environnementales",
    "Ingénieur en vision par ordinateur pour la robotique",
    "Architecte de données de la logistique",
    "Spécialiste en intégration de données IoT",
    "Développeur de solutions d'apprentissage automatique pour la finance",
    "Analyste en recommandation de produits",
    "Ingénieur en traitement de données sociales",
    "Consultant en stratégie d'analyse de données",
    "Architecte de données de la santé",
    "Spécialiste en apprentissage automatique pour la cybersécurité",
    "Développeur de logiciels d'analyse de données de vente au détail",
    "Ingénieur en vision par ordinateur industrielle",
    "Analyste en optimisation des processus",
    "Ingénieur en traitement de données de l'énergie",
    "Architecte de données du secteur public",
    "Spécialiste en intégration de données de santé",
    "Développeur de solutions de traitement de données financières",
    "Analyste en détection de tendances",
    "Ingénieur en traitement de données audio",
    "Architecte de solutions d'apprentissage automatique pour la logistique",
    "Spécialiste en bases de données graphes",
    "Développeur de logiciels d'analyse de données de l'industrie",
    "Ingénieur en vision par ordinateur pour les véhicules autonomes",
    "Analyste de données en assurance qualité",
    "Consultant en gouvernance des données",
    "Architecte de données du secteur de l'éducation",
    "Spécialiste en apprentissage automatique pour la santé mentale",
    "Développeur de logiciels d'analyse de données agricoles",
    "Ingénieur en traitement de données géologiques",
    "Analyste en segmentation de marché",
    "Ingénieur en traitement de données climatiques",
    "Architecte de solutions d'apprentissage automatique pour les ressources humaines",
    "Spécialiste en bases de données temps réel",
    "Développeur de logiciels de traitement du langage naturel médical",
    "Ingénieur en vision par ordinateur pour la surveillance",
    "Analyste en analyse des risques",
    "Consultant en stratégie d'IA",
    "Architecte de données de la publicité",
    "Spécialiste en fouille de données temporelles",
    "Développeur de solutions d'apprentissage automatique pour les jeux",
    "Analyste en expérience utilisateur basée sur les données",
    "Ingénieur en traitement de données de la chaîne d'approvisionnement",
    "Architecte de solutions de données de l'Internet des objets",
    "Spécialiste en apprentissage automatique pour la génomique",
    "Développeur de logiciels d'analyse de données de l'énergie",
    "Ingénieur en vision par ordinateur pour la surveillance vidéo",
   ]
jobs_web_dev = [
    "Développeur web",
    "Développeur front-end",
    "Développeur back-end",
    "Développeur full-stack",
    "Développeur JavaScript",
    "Développeur PHP",
    "Développeur Python",
    "Développeur Ruby",
    "Développeur Java",
    "Développeur C#",
    "Développeur HTML/CSS",
    "Développeur Angular",
    "Développeur React",
    "Développeur Vue.js",
    "Développeur Node.js",
    "Développeur WordPress",
    "Développeur Drupal",
    "Développeur Magento",
    "Développeur Laravel",
    "Développeur ASP.NET",
    "Développeur Ruby on Rails",
    "Développeur Django",
    "Développeur Express.js",
    "Développeur Mean Stack",
    "Développeur Mern Stack",
    "Développeur de thèmes WordPress",
    "Développeur de plugins WordPress",
    "Développeur e-commerce",
    "Développeur Shopify",
    "Développeur PrestaShop",
    "Développeur Joomla",
    "Développeur web mobile",
    "Développeur d'applications React Native",
    "Développeur d'applications Flutter",
    "Développeur d'applications Ionic",
    "Développeur d'applications iOS",
    "Développeur d'applications Android",
    "Développeur web junior",
    "Développeur web senior",
    "Développeur web freelance",
    "Développeur web à distance",
    "Développeur web indépendant",
    "Développeur web à temps partiel",
    "Développeur web à temps plein",
    "Architecte web",
    "Designer web",
    "Intégrateur web",
    "Spécialiste en expérience utilisateur (UX)",
    "Spécialiste en accessibilité web",
    "Spécialiste en sécurité web",
    "Spécialiste en référencement web",
    "Gestionnaire de projet web",
    "Testeur web",
    "Administrateur système web",
    "Analyste en optimisation des performances web",
    "Consultant en développement web",
    "Formateur en développement web",
    "Évangéliste web",
    "Spécialiste en commerce électronique",
    "Développeur de jeux web",
    "Développeur web en réalité virtuelle",
    "Développeur web en réalité augmentée",
    "Développeur web en intelligence artificielle",
    "Développeur web en blockchain",
    "Développeur web en cloud computing",
    "Développeur web en IoT (Internet des objets)",
    "Développeur web en chatbots",
    "Développeur web en automatisation des processus",
    "Développeur web en apprentissage automatique",
    "Développeur web en traitement du langage naturel",
    "Développeur web en vision par ordinateur",
    "Développeur web en Big Data",
    "Développeur web en réalité mixte",
    "Développeur web en cybersécurité",
    "Développeur web en marketing numérique",
   
  "Développeur web en marketing numérique",
    "Développeur web en gestion de contenu",
    "Développeur web en médias sociaux",
    "Développeur web en gestion des données",
    "Développeur web en analytique web",
    "Développeur web en e-learning",
    "Développeur web en réalité virtuelle",
    "Développeur web en réalité augmentée",
    "Développeur web en intelligence artificielle",
    "Développeur web en blockchain",
    "Développeur web en cloud computing",
    "Développeur web en IoT (Internet des objets)",
    "Développeur web en chatbots",
    "Développeur web en automatisation des processus",
    "Développeur web en apprentissage automatique",
    "Développeur web en traitement du langage naturel",
    "Développeur web en vision par ordinateur",
    "Développeur web en Big Data",
    "Développeur web en réalité mixte",
    "Développeur web en cybersécurité",
    "Développeur web en marketing numérique",
    "Développeur web en gestion de contenu",
    "Développeur web en médias sociaux",
    "Développeur web en gestion des données",
    "Développeur web en analytique web",
    "Développeur web en e-learning",
    "Développeur web en intelligence d'affaires",
    "Développeur web en intelligence émotionnelle",
    "Développeur web en localisation",
    "Développeur web en automatisation des tests",
    "Développeur web en optimisation des moteurs de recherche",
    "Développeur web en réalité étendue",
    "Développeur web en traitement d'image",
    "Développeur web en accessibilité numérique",
    "Développeur web en développement durable",
    "Développeur web en commerce électronique",
    "Développeur web en médias interactifs",
    "Développeur web en storytelling numérique",
    "Développeur web en expérience utilisateur (UX) mobile",
    "Développeur web en intelligence de localisation",
    "Développeur web en personnalisation de contenu",
    "Développeur web en recommandation de produits",
    "Développeur web en gestion des API",
    "Développeur web en gestion de la qualité",
    "Développeur web en gestion de projet",
    "Développeur web en développement de prototypes",
    "Développeur web en conception de sites web",
    "Développeur web en optimisation de conversion",
    "Développeur web en gamification",
    "Développeur web en génération de leads",
    "Développeur web en marketing automation",
    "Développeur web en traitement des paiements en ligne",
    "Développeur web en sécurité des paiements en ligne",
    "Développeur web en développement de modules complémentaires",
    "Développeur web en extensions de navigateur",
    "Développeur web en microservices",
    "Développeur web en déploiement continu",

]








jobs_cloud_devops = [
    "Ingénieur DevOps",
    "Architecte cloud",
    "Administrateur cloud",
    "Développeur cloud",
    "Spécialiste DevOps",
    "Ingénieur de fiabilité du site (SRE)",
    "Administrateur système cloud",
    "Ingénieur cloud sécurité",
    "Ingénieur cloud réseau",
    "Consultant cloud",
    "Spécialiste en automatisation DevOps",
    "Développeur d'infrastructure cloud",
    "Ingénieur de déploiement cloud",
    "Architecte de solutions cloud",
    "Ingénieur de migration cloud",
    "Ingénieur de conteneurisation",
    "Ingénieur de l'orchestration cloud",
    "Développeur AWS",
    "Architecte AWS",
    "Administrateur AWS",
    "Spécialiste AWS",
    "Développeur Azure",
    "Architecte Azure",
    "Administrateur Azure",
    "Spécialiste Azure",
    "Développeur Google Cloud Platform",
    "Architecte Google Cloud Platform",
    "Administrateur Google Cloud Platform",
    "Spécialiste Google Cloud Platform",
    "Ingénieur en automatisation de l'infrastructure",
    "Ingénieur de sécurité DevOps",
    "Ingénieur de performance cloud",
    "Ingénieur de gestion des coûts cloud",
    "Spécialiste en intégration et déploiement continus (CI/CD)",
    "Architecte de conteneurisation",
    "Ingénieur Kubernetes",
    "Spécialiste en orchestration de conteneurs",
    "Ingénieur de la supervision cloud",
    "Ingénieur en haute disponibilité",
    "Architecte de microservices",
    "Ingénieur en gestion des logs",
    "Développeur de scripts d'automatisation",
    "Ingénieur en sauvegarde et récupération cloud",
    "Architecte de sécurité cloud",
    "Ingénieur de tolérance aux pannes",
    "Ingénieur en gestion des configurations",
    "Développeur de solutions de surveillance cloud",
    "Architecte de réseau cloud",
    "Ingénieur en déploiement continu",
    "Ingénieur en migration de données cloud",
    "Développeur Terraform",
    "Spécialiste en infrastructure as code",
    "Ingénieur en gestion des secrets",
    "Ingénieur en résilience",
    "Ingénieur en optimisation des coûts cloud",
    "Développeur de solutions serverless",
    "Ingénieur en gestion des changements",
    "Spécialiste en intégration d'API",
    "Développeur Ansible",
    "Ingénieur de la performance des applications cloud",
    "Architecte de migration cloud",
    "Développeur Puppet",
    "Ingénieur en gestion des tests cloud",
    "Spécialiste en intégration continue",
    "Ingénieur en déploiement cloud hybride",
    "Développeur Chef",
    "Ingénieur en gestion des versions",
    "Spécialiste en gestion des configurations",
    "Ingénieur en déploiement multi-cloud",
    "Architecte de sécurité des infrastructures cloud",
    "Développeur Jenkins",
    "Ingénieur de la livraison continue",

    "Spécialiste en gestion de la capacité cloud",]








jobs_software_dev = [
    "Développeur de logiciels",
    "Développeur front-end",
    "Développeur back-end",
    "Développeur full-stack",
    "Développeur Java",
    "Développeur Python",
    "Développeur C++",
    "Développeur C#",
    "Développeur JavaScript",
    "Développeur PHP",
    "Développeur Ruby",
    "Développeur Swift",
    "Développeur Objective-C",
    "Développeur Kotlin",
    "Développeur TypeScript",
    "Développeur Rust",
    "Développeur Go",
    "Développeur Scala",
    "Développeur R",
    "Développeur MATLAB",
    "Développeur Perl",
    "Développeur Groovy",
    "Développeur Dart",
    "Développeur Lua",
    "Développeur COBOL",
    "Développeur ABAP",
    "Développeur PL/SQL",
    "Développeur Pascal",
    "Développeur Shell",
    "Développeur VBA",
    "Développeur Assembly",
    "Développeur Delphi",
    "Développeur Fortran",
    "Développeur RPG",
    "Développeur Ada",
    "Développeur VHDL",
    "Développeur LabVIEW",
    "Développeur Simulink",
    "Développeur Unity",
    "Développeur Unreal Engine",
    "Développeur Android",
    "Développeur iOS",
    "Développeur Windows",
    "Développeur Linux",
    "Développeur macOS",
    "Développeur de jeux vidéo",
    "Développeur web",
    "Développeur mobile",
    "Développeur d'applications",
    "Développeur de logiciels embarqués",
    "Développeur d'intelligence artificielle",
    "Développeur de réalité virtuelle",
    "Développeur de réalité augmentée",
    "Développeur d'applications de bureau",
    "Développeur de systèmes",
    "Développeur de bases de données",
    "Développeur de microservices",
    "Développeur d'automatisation",
    "Développeur de tests logiciels",
    "Développeur de sécurité logicielle",
    "Développeur de systèmes embarqués",
    "Développeur de systèmes d'exploitation",
    "Développeur de jeux mobiles",
    "Développeur de logiciels CRM",
    "Développeur de logiciels ERP",
    "Développeur de logiciels de gestion de projet",
    "Développeur de logiciels de CAO",
    "Développeur de logiciels de simulation",
    "Développeur de logiciels de visualisation de données",
    "Développeur de logiciels de traitement d'images",
    "Développeur de logiciels de traitement du langage naturel",
    "Développeur de logiciels de reconnaissance vocale",
  "Développeur de logiciels de traitement de signal",
    "Développeur de logiciels de vision par ordinateur",
    "Développeur de logiciels de bioinformatique",
    "Développeur de logiciels de finance",
    "Développeur de logiciels de santé",
    "Développeur de logiciels de gestion des ressources humaines",
    "Développeur de logiciels de gestion de la chaîne d'approvisionnement",
    "Développeur de logiciels de CRM",
    "Développeur de logiciels de marketing",
    "Développeur de logiciels de gestion de contenu",
    "Développeur de logiciels de commerce électronique",
    "Développeur de logiciels de jeux vidéo",
    "Développeur de logiciels de réalité virtuelle",
    "Développeur de logiciels de réalité augmentée",
    "Développeur de logiciels de sécurité",
    "Développeur de logiciels de détection d'intrusion",
    "Développeur de logiciels de chiffrement",
    "Développeur de logiciels de gestion de réseau",
    "Développeur de logiciels de gestion de bases de données",
    "Développeur de logiciels de veille technologique",
    "Développeur de logiciels de traitement des données",
    "Développeur de logiciels de business intelligence",
    "Développeur de logiciels de planification des ressources d'entreprise",
    "Développeur de logiciels de suivi des performances",
    "Développeur de logiciels de gestion des incidents",
    "Développeur de logiciels de gestion de projets",
    "Développeur de logiciels de collaboration",
    "Développeur de logiciels de gestion des connaissances",
    "Développeur de logiciels de support client",
    "Développeur de logiciels de gestion de tickets",
    "Développeur de logiciels de workflow",
    "Développeur de logiciels de modélisation",
    "Développeur de logiciels de simulation",
    "Développeur de logiciels de modélisation 3D",
    "Développeur de logiciels de reconnaissance faciale",
    "Développeur de logiciels de traduction automatique",
    "Développeur de logiciels de moteur de recherche",
    "Développeur de logiciels de recommandation",
    "Développeur de logiciels de chatbot",
    "Développeur de logiciels de traitement automatique du langage naturel",
    "Développeur de logiciels de gestion de la relation client",
    "Développeur de logiciels de gestion de projets",
    "Développeur de logiciels de gestion des ressources humaines",
    "Développeur de logiciels de gestion de la chaîne logistique",
    "Développeur de logiciels de gestion des opérations",
    "Développeur de logiciels de gestion de contenu",]

keywordsT= [
    # Concepts
    "Science des données",
    "Apprentissage automatique",
    "Apprentissage profond",
    "Réseaux de neurones",
    "Traitement du langage naturel",
    "Fouille de données",
    "Analyse de données",
    "Visualisation de données",
    "Intelligence artificielle",
    "Gros données",
    
    # Tools & Libraries
    "SQL",
    "Python",
    "R",
    "Java",
    "Hadoop",
    "Apache Spark",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Tableau",
    "Power BI",
    
    # Data Engineering & Database
    "Ingénierie des données",
    "ETL",
    "Entrepôt de données",
    "Administration de base de données",
    "Architecture de données",
    "Modélisation de données",
    
    # Cloud Computing
    "Informatique en nuage",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    
    # Job Titles
    "Analyste de données",
    "Analyste de la qualité des données",
    "Architecte de données",
    "Chercheur en apprentissage automatique",
    "Chercheur en intelligence artificielle",
    "Consultant en analyse de données",
    "Scientifique des données",
    "Développeur d'apprentissage automatique",
    "Développeur de logiciels d'intelligence artificielle",
    "Expert en visualisation de données",
    "Ingénieur en données",
    "Ingénieur en apprentissage automatique",
    "Spécialiste de gros données",
    "Spécialiste en traitement du langage naturel",
    "Statisticien",
    "Concepteur de plateforme de données",
    "Développeur de pipeline de données",
    "Développeur de logiciels de traitement de données",
    "Développeur de systèmes de base de données",
    "Développeur de systèmes d'information",
    "Développeur Python",
    "Développeur Java",
    "Développeur SQL",
    "Développeur Hadoop",
    "Développeur TensorFlow",
    "Développeur Keras",
    "Développeur PyTorch",
    "Administrateur AWS",
    "Architecte Azure",
    "Spécialiste de Google Cloud Platform"
]
keywordsDev = [
    # Concepts
    "Développement web",
    "Développement mobile",
    "Responsive design",
    "UI/UX",
    "Frontend",
    "Backend",
    "Full-stack",

    # Outils & Langages
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "PHP",
    "Ruby on Rails",
    "Django",
    "Flask",
    "Java",
    "Kotlin",
    "Swift",
    "Objective-C",
    "TypeScript",
    "SQL",
    "NoSQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Firebase",

    # Cloud Computing
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Firebase",
    "Heroku",

    # Titres de poste
    "Développeur web",
    "Développeur frontend",
    "Développeur backend",
    "Développeur full-stack",
    "Développeur mobile",
    "Développeur Android",
    "Développeur iOS",
    "Développeur React",
    "Développeur Angular",
    "Développeur Vue.js",
    "Développeur JavaScript",
    "Développeur Java",
    "Développeur Kotlin",
    "Développeur Swift",
    "Développeur Objective-C",
    "Développeur PHP",
    "Développeur Ruby on Rails",
    "Développeur Django",
    "Développeur Flask",
    "Développeur Node.js",
    "Développeur TypeScript",
    "Développeur SQL",
    "Développeur MySQL",
    "Développeur PostgreSQL",
    "Développeur MongoDB",
    "Développeur Firebase",
    "Architecte logiciel",
    "Architecte de solutions cloud",
    "Ingénieur logiciel",
    "Ingénieur DevOps",
    "Administrateur de base de données",
    "Designer UI/UX"
]


keywords_software_dev = [
    "Développement de logiciels",
    "Développeur de logiciels",
    "Programmation",
    "Codage",
    "Architecture logicielle",
    "Ingénierie logicielle",
    "Conception logicielle",
    "Débogage",
    "Tests logiciels",
    "Optimisation des performances",
    "Maintenance logicielle",
    "Développement mobile",
    "Application mobile",
    "Développeur mobile",
    "iOS",
    "Android",
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Objective-C",
    "Java",
    "Xcode",
    "Android Studio",
    "Interface utilisateur mobile",
    "Expérience utilisateur mobile",
    "Science des données",
    "Analyse de données",
    "Traitement de données",
    "Apprentissage automatique",
    "Apprentissage profond",
    "Réseaux de neurones",
    "Traitement du langage naturel",
    "Fouille de données",
    "Visualisation de données",
    "Big data",
    "Python",
    "R",
    "SQL",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Statistiques",
    "Data mining",
    "Analyse prédictive",
    "Analyse exploratoire des données",
    "Modélisation de données",
    "Prétraitement des données",
    "Nettoyage des données",
    "Algorithmes",
    "Visualisation graphique",
    "Tableau de bord",
    "Intelligence artificielle",
    "Cloud computing",
    "DevOps",
    "Méthodes agiles"
]
keywords_mobile_dev = [
    "Développement d'applications mobiles",
    "Développement natif",
    "Développement hybride",
    "Conception d'interfaces mobiles",
    "Expérience utilisateur mobile",
    "Développeur iOS",
    "Développeur Android",
    "Développeur React Native",
    "Développeur Flutter",
    "Développeur Swift",
    "Développeur Kotlin",
    "Développeur Objective-C",
    "Développeur Java",
    "Développeur d'applications mobiles",
    "Développeur d'applications iOS",
    "Développeur d'applications Android",
    "Développeur d'applications hybrides",
    "Développeur d'interfaces utilisateur mobiles",
    "Développeur d'expérience utilisateur mobile",
    "Développeur de jeux mobiles",
    "Développeur de réalité augmentée mobile",
    "Développeur de réalité virtuelle mobile",
    "Développeur de technologies mobiles émergentes",
    "Développeur d'applications IoT",
    "Développeur de solutions de paiement mobile",
    "Développeur de localisation mobile",
    "Développeur de messagerie mobile",
    "Développeur de médias sociaux mobiles",
    "Développeur de services de localisation mobiles",
    "Développeur de commerce électronique mobile",
    "Développeur de géolocalisation mobile",
    "Développeur de services de messagerie mobiles",
    "Développeur de services bancaires mobiles",
    "Développeur de jeux multijoueurs mobiles",
    "Développeur de services de médias mobiles",
    "Développeur de réseaux sociaux mobiles",
    "Développeur de technologies mobiles sans fil",
    "Développeur de services de santé mobiles",
    "Développeur de portefeuilles mobiles",
    "Développeur de services de voyage mobiles",
    "Développeur de services de musique mobiles",
    "Développeur de services de vidéo mobiles",
    "Développeur de services de transport mobiles",
    "Développeur de services de rencontres mobiles",
    "Développeur de services de livraison mobiles",
    "Développeur de services de réservation mobiles",
    "Développeur de services de fitness mobiles",
    "Développeur de services de réalité mixte mobiles",
    "Développeur de services de réalité étendue mobiles",
    "Développeur de services de réalité immersive mobiles",
]

keywords_data_science = [
    "Science des données",
    "Analyse de données",
    "Traitement de données",
    "Apprentissage automatique",
    "Apprentissage profond",
    "Réseaux de neurones",
    "Traitement du langage naturel",
    "Fouille de données",
    "Visualisation de données",
    "Big data",
    "Python",
    "R",
    "SQL",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Statistiques",
    "Data mining",
    "Analyse prédictive",
    "Analyse exploratoire des données",
    "Modélisation de données",
    "Prétraitement des données",
    "Nettoyage des données",
    "Algorithmes",
    "Visualisation graphique",
    "Tableau de bord",
    "Intelligence artificielle",
    "Apprentissage automatique supervisé",
    "Apprentissage automatique non supervisé",
    "Apprentissage par renforcement",
    "Analyse de texte",
    "Traitement du langage naturel",
    "Reconnaissance d'entités nommées",
    "Classification",
    "Regroupement",
    "Régression",
    "Réseau de neurones",
    "Deep learning",
    "Ensemble learning",
    "Sélection de fonctionnalités",
    "Validation croisée",
    "Évaluation des modèles",
    "Apprentissage en ligne",
    "Apprentissage incrémental",
    "Visualisation de données",
    "Tableau de bord",
    "Exploration de données",
    "Extraction de caractéristiques",
    "Prévision",
    "Détection d'anomalies",
    "Recommandation",
    "Optimisation",
    "Validation des modèles",
    "Analyse de sentiments",
    "Traitement du langage naturel",
    "Apprentissage profond",
    "Traitement automatique du langage naturel",
    "Apprentissage par renforcement",
    "Apprentissage non supervisé",
    "Réseau de neurones convolutifs",
    "Réseau de neurones récurrents",
    "Réseau de neurones générateurs adverses",
    "Réseau de neurones transformateurs",
    "Traitement d'image",
    "Traitement du signal",
    "Analyse de séries temporelles",
    "Analyse de données géospatiales",
    "Analyse de graphes",
    "Apprentissage en ligne",
    "Analyse de données non structurées",
    "Apprentissage supervisé",
    "Apprentissage non supervisé",
    "Apprentissage semi-supervisé",
    "Apprentissage renforcé",
    "Algorithmes d'optimisation",
    "Réseaux bayésiens",
    "Modèles de Markov cachés",
    "Systèmes de recommandation",
    "Apprentissage par transfert",
    "Apprentissage profond à grande échelle",
    "Analyse de données massives",
    "Apprentissage en profondeur",
    "Modèles génératifs",
    "Reconnaissance de formes",
    "Analyse de données génomiques",
    "Analyse de données médicales",
    "Analyse de données financières",
    "Analyse de données de vente",
    "Analyse de données marketing",
    "Analyse de données de réseaux sociaux",
    "Analyse de données de jeux vidéo",
    "Analyse de données de trafic",
    "Analyse de données de transport",
    "Analyse de données de fraudes",
    "Analyse de données de cybersécurité",]

keywordsT= [
    # Data Science
    "Machine learning",
    "Deep learning",
    "Neural networks",
    "Natural language processing",
    "Data mining",
    "Data analysis",
    "Data visualization",
    "Statistics",
    "Predictive modeling",
    "Artificial intelligence",
    "Big data",
    "Business intelligence",
    "Hadoop",
    "Spark",
    "SQL",
    "Python",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "NLTK",
    "SpaCy",
    "Gensim",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "AutoML",
    "Data Engineering",
    "ETL",
    "Data warehousing",
    "Data pipelines",
    "Database administration",
    "Data architecture",
    "Data modeling",
    "Data integration",
    "Data quality",
    "Data governance",
    "Cloud computing",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Amazon Web Services",
    "Cloud security",
    "Cloud architecture",
    "Cloud migration",
    "Cloud deployment",
    "Serverless computing",
    "Virtual machines",
    "Containers",
    "Kubernetes",
    "Infrastructure as Code",
    "IaaS",
    "PaaS",
    "SaaS",
    "HTML",
    "CSS",
    "JavaScript",
    "jQuery",
    "React",
    "AngularJS",
    "Node.js",
    "Express.js",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Django",
    "Flask",
    "Bootstrap",
    "RESTful APIs",
    "GCP",
    "React Native",
    "TypeScript",
    "Android",
    "iOS",
    "Kotlin",
    "Swift",
    "Objective-C",
    "Firebase",
    "Mobile app development",
    "Data Analyst",
    "Data Quality Analyst",
    "Data Architect",
    "Machine Learning Researcher",
    "Artificial Intelligence Researcher",
    "Data Analysis Consultant",
    "Data Scientist",
    "Machine Learning Developer",
    "Artificial Intelligence Software Developer",
    "Data Visualization Expert",
    "Data Engineer",
    "Machine Learning Engineer",
    "Big Data Specialist",
    "Natural Language Processing Specialist",
    "Statistician",
    "Data Platform Designer",
    "Data Pipeline Developer",
    "Data Processing Software Developer",
    "Database Systems Developer",
    "Information Systems Developer",
    "Deep Learning Engineer",
    "Neural Networks Engineer",
    "AutoML Expert",
    "Machine Learning Model Developer",
    "Deep Learning Model Developer",
    "Développeur Angular",
    "Développeur API RESTful",
    "Développeur AWS",
    "Développeur Azure",
    "Développeur Bootstrap",
    "Développeur CSS",
    "Développeur de sites Web",
    "Développeur Django",
    "Développeur Express.js",
    "Développeur Flask",
    "Développeur GCP",
    "Développeur HTML",
    "Développeur JavaScript",
    "Développeur jQuery",
    "Développeur MongoDB",
    "Développeur MySQL",
    "Développeur Node.js",
    "Développeur PostgreSQL",
    "Développeur React"]
# Access the username and password values