T = [
# Data Science
"Machine learning",
"Deep learning",
"Neural networks",
"Natural language processing",
"Data mining",
"Data analysis",
"Data visualization",
"Statistics",
"Predictive modeling",
"Artificial intelligence",
"Big data",
"Business intelligence",
"Hadoop",
"Spark",
"SQL",
"Python",
"Scikit-learn",
"TensorFlow",
"Keras",
"PyTorch",
"Pandas",
"NumPy",
"Matplotlib",
"Seaborn",
"NLTK",
"SpaCy",
"Gensim",
"XGBoost",
"LightGBM",
"CatBoost",
"AutoML",
"Data Engineering",
"ETL",
"Data warehousing",
"Data pipelines",
"Database administration",
"Data architecture",
"Data modeling",
"Data integration",
"Data quality",
"Data governance",
"Cloud computing",
"AWS",
"Azure",
"Google Cloud Platform",
"Microsoft Azure",
"Amazon Web Services",
"Cloud security",
"Cloud architecture",
"Cloud migration",
"Cloud deployment",
"Serverless computing",
"Virtual machines",
"Containers",
"Kubernetes",
"Infrastructure as Code",
"IaaS",
"PaaS",
"SaaS",
"HTML",
"CSS",
"JavaScript",
"jQuery",
"React",
"AngularJS",
"Node.js",
"Express.js",
"MongoDB",
"MySQL",
"PostgreSQL",
"Django",
"Flask",
"Bootstrap",
"RESTful APIs",
"GCP",
"React Native",
"TypeScript",
"Android",
"iOS",
"Kotlin",
"Swift",
"Objective-C",
"Firebase",
"Mobile app development",
"Data Analyst",
"Data Quality Analyst",
"Data Architect",
"Machine Learning Researcher",
"Artificial Intelligence Researcher",
"Data Analysis Consultant",
"Data Scientist",
"Machine Learning Developer",
"Artificial Intelligence Software Developer",
"Data Visualization Expert",
"Data Engineer",
"Machine Learning Engineer",
"Big Data Specialist",
"Natural Language Processing Specialist",
"Statistician",
"Data Platform Designer",
"Data Pipeline Developer",
"Data Processing Software Developer",
"Database Systems Developer",
"Information Systems Developer",
"Deep Learning Engineer",
"Neural Networks Engineer",
"AutoML Expert",
"Machine Learning Model Developer",
"Deep Learning Model Developer",
"Angular Developer",
"RESTful API Developer",
"AWS Developer",
"Azure Developer",
"Bootstrap Developer",
"CSS Developer",
"Web Developer",
"Django Developer",
"Express.js Developer",
"Flask Developer",
"GCP Developer",
"HTML Developer",
"JavaScript Developer",
"jQuery Developer",
"MongoDB Developer",
"MySQL Developer",
"Node.js Developer",
"PostgreSQL Developer",
"React Developer"
]
